---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcox
  namespace: grpcox
spec:
  selector:
    matchLabels:
      run: grpcox
  replicas: 1
  template:
    metadata:
      labels:
        run: grpcox
    spec:
      containers:
        - name: grpcox
          image: gusaul/grpcox
          resources:
            requests:
              memory: "64Mi"
              cpu: "75m"
            limits:
              memory: "128Mi"
              cpu: "200m"
